// VERP (Variable Envelope Return Path) — encodes which campaign+recipient a
// send belongs to directly into the SMTP envelope sender, so a bounce DSN
// generated by the recipient's mail server comes back addressed to an
// address that identifies exactly what bounced, with no need to parse
// "Original-Recipient" out of the DSN body itself. See mailer.ts's
// `envelopeFrom` and mta/'s Postfix transport that routes these back to
// POST /webhooks/bounce/postfix.
//
// Format: bounce.{campaignId}.{base64url(email)}@{bounceDomain}
// A single "." separates the two data segments — base64url's alphabet never
// contains ".", so this can't be ambiguous, and RFC 5321 allows an unquoted
// "." between other atext as long as it's not leading/trailing/doubled.
const LOCAL_PART_RE = /^bounce\.(\d+)\.([A-Za-z0-9_-]+)$/;

export function makeVerpAddress(campaignId: number, email: string, bounceDomain: string): string {
  const encoded = Buffer.from(email.toLowerCase()).toString("base64url");
  return `bounce.${campaignId}.${encoded}@${bounceDomain}`;
}

export function parseVerpAddress(address: string): { campaignId: number; email: string } | null {
  const localPart = address.split("@")[0] ?? "";
  const match = LOCAL_PART_RE.exec(localPart);
  if (!match) return null;
  try {
    const email = Buffer.from(match[2], "base64url").toString("utf-8");
    return { campaignId: Number(match[1]), email };
  } catch {
    return null;
  }
}
